version: '3.7'

services:

  api:
    image: codait/max-facial-age-estimator:latest
    stdin_open: true
    tty: true
    ports:
      - 5010:5000
      - 8010:8000

  web:
    image: codait/max-facial-age-estimator-mini-web-app:latest
    network_mode: service:api
